### ISSUE TITLE
Periodic error

### ISSUE THREAD

**Issue by edalzell** [kijin/pinboard-api#10]
I see this error in my logs periodically:

```
[2016-10-13 05:50:12] production.ERROR: exception 'ErrorException'
with message 'Invalid argument supplied for foreach()' in
/home/edalzell/thedalzells.org/statamic/vendor/kijin/pinboard-api/pinboard-api.php:432
Stack trace: #0
```

Perhaps a bit more param checking is needed?

**Comment by edalzell** [comment]
Maybe an `ensureArray` helper??

**Comment by kijin** [comment]
Wrapping the loop in `if (is_array($json))` would help get rid of the error, but I'd like to know exactly what's in `$json` that causes the problem.

Most of the usual error conditions are supposed to result in an exception earlier on, so if anything is getting through that isn't an array, perhaps it should be handled in another place.

Could you add some error handlers to dump that variable the next time it happens?

**Comment by edalzell** [comment]
ok, going to try:
```
       if (!is_array($json))
        {
            ob_start();
            var_dump($json);
            \Log::error(ob_get_contents());
            ob_end_clean();
        }
```

**Comment by edalzell** [comment]
`$json` is null, which means this code produces null:
```
        $json = $this->_remote('posts/all', $args);
        return $this->_json_to_bookmark($json);
```

**Comment by edalzell** [comment]
if it helps, I'm calling `get_all`:
```
			$pinboard = new PinboardAPI(null, $token);
		
			$bookmarks = $pinboard->get_all(null, null, $tag, $timestamp);
```

**Comment by kijin** [comment]
It seems Pinboard is returning an invalid response from time to time that we're not catching properly. I will add some more error checking so invalid responses always throw a `PinboardException_InvalidResponse` before any further processing.
