### ISSUE TITLE
API token case

### ISSUE THREAD

**Issue by fiveminuteargument** [kijin/pinboard-api#9]
The API token, as currently displayed on the pinboard settings page, includes lowercase letters. The regex in this library (and, to be fair, the documentation) assumes uppercase only.

**Comment by kijin** [comment]
Huh, that's strange. I tried resetting my token a few times and never found any lowercase letters.

Anyway, can you confirm that if you change the regex to accept lowercase letters, the API actually accepts your lowercase token?

**Comment by fiveminuteargument** [comment]
Sorry, I dropped the ball on this one. Yes, I can confirm that changing the regexp substring from

`':[0-9A-F]{20}$/'`

to

`':[0-9A-Fa-f]{20}$/'`

resolves the issue. Moreover, if I manually convert my API token to uppercase, it also works, so the token is case-sensitive as far as pinboard itself is concerned, just that pinboard-api currently requires it to be all-uppercase.

FWIW, I don't think I've ever reset my API token, so it might just be that the initial value can contain lowercase letters, but resetting it guarantees uppercase.

**Comment by fiveminuteargument** [comment]
Just to follow-up on that, it *does* appear that the initial token can contain lowercase letters, but subsequently-reset tokens *do not*. Which is quite weird; I've pinged off a report to support@pinboard.in about it.

**Comment by kijin** [comment]
> Moreover, if I manually convert my API token to uppercase, it also works, so the token is case-sensitive as far as pinboard itself is concerned

You mean the token is *case-insensitive*, right?

Anyway, since Pinboard does seem to be both issuing and accepting tokens with lowercase letters, whether intentionally or not, I'll change the regex to accept them.
